#!/bin/bash

# redirect stderr->stdout
exec 2>&1

# runsvdir-start clears environment variables
# initially import all variables
source /env.bash

# start master (if not running)
if ! $(ps aux | rgrep -q "spark-assembly"); then
  $SPARK_HOME/sbin/start-master.sh
fi
