#!/bin/bash

# redirect stderr->stdout
exec 2>&1

# runsvdir-start clears environment variables
# initially import all variables
source /env.bash

# optional spark worker configuration
#export SPARK_WORKER_CONFIG="--num-executors 6 --executor-memory 4g --executor-cores 12"

# start notebook and connect to master (if not running)
cd /ipython
su - $CONTAINER_USER --preserve-environment -c "PYSPARK_DRIVER_PYTHON=ipython IPYTHON_OPTS=\"notebook --profile spark\" $SPARK_HOME/bin/pyspark --master $SPARK_MASTER $SPARK_WORKER_CONFIG"
